### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by REBELinBLUE** [kishaningithub/setup-tf-summarize#49] opened 2023-10-25 12:47 UTC
When trying to use the workflow I get the following error

```
downloading tf-summarize from https://github.com/dineshba/tf-summarize/releases/download/v0.3.6/tf-summarize_linux_amd64.zip
Error: Unexpected HTTP response: 404
```

A quick look at https://github.com/dineshba/tf-summarize/releases/tag/v0.3.6 reveals that in 0.3.6 it has been uploaded as tar.gz whereas in https://github.com/dineshba/tf-summarize/releases/tag/v0.3.5 it was uploaded as a zip

**Comment by kishaningithub** [comment] 2023-10-25 14:35
Yeah you are right. This was the change which caused this tool to break

https://github.com/dineshba/tf-summarize/issues/52

Will fix this soon

**Comment by kishaningithub** [comment] 2023-10-25 19:25
@REBELinBLUE The issue is fixed and released in v1.0.1 Let me know if you see any issues

**Comment by kishaningithub** [comment] 2023-10-26 03:54
Closing this issue now. feel free to reopen it if you think the issue persists

**Closed** 2023-10-26 03:54 UTC

**Comment by REBELinBLUE** [comment] 2023-10-26 08:48
thanks
